### ISSUE TITLE
Building haru

### ISSUE THREAD

**Issue by KaitoZero76** [if1live/haru#1]
Hi. I am interesting in building haru on macOS but I can't actually build it. How would I go around doing so? I can build haru-cli with no problems but running `go build` doesn't output anything in ./haru

I would appreciate any help you can give. I think this is my best way to export tags to JSON from hitomi.la so that is why I am interested. Thanks!

**Comment by if1live** [comment]
Haru is library, not applicaion. Haru doesn't have main function, so you can't make executable file.

You should use haru-cli or make your own crawler. I hope that this library useful to you.

**Comment by KaitoZero76** [comment]
OK. Thank you!
