### ISSUE TITLE
Why parse html?

### ISSUE THREAD

**Issue by isairz** [if1live/haru#2]
It provides JSON happily.
`히토미/galleries0.json`
`히토미/galleries/${id}.js`

**Comment by if1live** [comment]
Good links. I check those now....

1. `히토미/galleries0.json` look likes useful, but it has too many information.

example...
* `sizeof(히토미/galleries/405092.html)` == 3.3KB
* `sizeof(히토미/galleries0.json)` == 1.1MB

Also, I can't get specific gallery information from that json.
json has many galleries, but it doesn't contains 405092.

2. `히토미/galleries/${id}.js` look likes useful. I will use it if I do refactoring.

**Comment by if1live** [comment]
I found 405092 from `히토미/galleries14.json`.
`히토미/galleries{page}.json` is useful if I dump hitomi completely.

**Comment by isairz** [comment]
Yes. hitomi server has 20 sharding databases (0~19), and can be increased when database 0 is full.
